version: "3"

services:
  mlflow:
    container_name: mlflow
    image: demand_forecasting_m5:demand_forecasting_m5_mlflow_1.0.0    
    volumes:
      - ./machine_learning/outputs/mlruns:/opt/outputs/mlruns
    networks:
      - default
    command:
      - "mlflow"
      - "server"
      - "--backend-store-uri"
      - "/opt/outputs/mlruns" 
      - "--default-artifact-root"
      - "/opt/outputs/mlruns"
      - "--host"
      - "0.0.0.0"
    ports:
      - 15000:5000
    restart: always
    hostname: mlflow

  bi:
    container_name: bi
    image: demand_forecasting_m5:demand_forecasting_m5_bi_1.0.0
    restart: "no"
    volumes:
      - ./bi/src:/opt/src
    networks:
      - default
    environment:
      - POSTGRES_HOST=dev-m5-postgres.postgres.database.azure.com
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password1!
      - POSTGRES_DBNAME=demand_forecasting_m5
    ports:
      - 8501:8501
    command: /bin/sh -c "sleep 20s && streamlit run src/main.py"
    depends_on:
      - mlflow

networks:
  default:
    name: demand_forecasting_m5
